# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AO5r0nDIbXUpV6K0MKxUVnxvZ56FVBw3
"""

import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

data = pd.read_csv('infy_stock.csv')

model = load_model('finals_model.h5')

def predict_stock_price(data, model):
    lags = 10
    input_data = data[-lags:].values.reshape(1, lags, 1)
    predicted_price = model.predict(input_data)
    return predicted_price[0][0]

st.title("Stock Price Prediction")

st.subheader("Stock Dataset")
st.write(data)

prediction = predict_stock_price(data['Trades'], model)

st.subheader("Predicted Stock Price")
st.write(prediction)

fig, ax = plt.subplots()
ax.plot(data['Date'], data['Trades'], label='Actual')
ax.axvline(data['Date'].iloc[-1], color='r', linestyle='--', label='Last Observation')
ax.axhline(prediction, color='g', linestyle='--', label='Predicted')
ax.set_xlabel('Date')
ax.set_ylabel('Stock Price')
ax.set_title('Stock Price Prediction')
ax.legend()
st.pyplot(fig)